### ISSUE TITLE
Once connected to KVM, there is no option/button to disconnect.

### ISSUE THREAD

**Issue by mtpham-1** [open-amt-cloud-toolkit/console#194]
![image](https://github.com/open-amt-cloud-toolkit/console/assets/140858054/de0c8ba5-59fc-40c9-b357-bfd6c2520f4b)

Reproduce steps…

![image](https://github.com/open-amt-cloud-toolkit/console/assets/140858054/95ba8b5d-313f-481c-b749-960d684d0eff)

**Comment by bwendlandt-intel** [comment]
Behavior occurs when starting a redirection session, both KVM and SOL, from the top-nav bar rather than from the right-hand side menu.

Implementation should be the same for both options. When starting a session from top-nav, it should still show the top-nav bar with redirection and power action controls.
